# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZGM4MTA5MjAzNDY0YTMxOWNjZjgzNzI0ZjNkNWRiYzM5NjI4MjJiOTM5OGMzMDFmNzhmMTc3Yjk1MzMzMjc2ZmZkMzE0ZGIzYTBhYzZkNWQ4ZjYxZTdkODYwMDczZmI3NWIzMzJlNjU1NzRjOWRhMTQzNjk3N2M3MjY3MjVlMmU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
